- hosts: all
  tasks:
  - debug:
      msg: "{{ inventory_hostname }}"

  - debug:
      msg: "{{ ansible_default_ipv4.address }}"

  - name: Update /etc/hosts file
    lineinfile:
      path: /etc/hosts
      line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }}"
      create: yes

      